### ISSUE TITLE
sound/pci/hda/patch_cirrus.c:1978:18: warning: unused variable ‘spec’

### ISSUE THREAD

**Issue by stefdb** [snake0x65/hda#2]
https://github.com/snake0x65/hda/blob/e44851ad85fe97370127432325b65d4b1cbdd2c3/patch_cirrus.c#L1978

sound/pci/hda/patch_cirrus.c: In function ‘cs8409_capture_pcm_hook’:
sound/pci/hda/patch_cirrus.c:1978:18: warning: unused variable ‘spec’ [-Wunused-variable]
 1978 |  struct cs_spec *spec = codec->spec;

**Comment by snake0x65** [comment]
Done
