### ISSUE TITLE
MIC Mute/Unmute Question

### ISSUE THREAD

**Issue by stefdb** [snake0x65/hda#5]
https://github.com/snake0x65/hda/blob/e44851ad85fe97370127432325b65d4b1cbdd2c3/patch_cirrus.c#L1654-L1655

https://github.com/snake0x65/hda/blob/e44851ad85fe97370127432325b65d4b1cbdd2c3/patch_cirrus.c#L1698-L1699

https://github.com/snake0x65/hda/blob/e44851ad85fe97370127432325b65d4b1cbdd2c3/patch_cirrus.c#L1929-L1935

https://github.com/snake0x65/hda/blob/e44851ad85fe97370127432325b65d4b1cbdd2c3/patch_cirrus.c#L1973

Does anything need to be muted/unmuted for the mic (NID 0x34) in any of these places/functions?

**Comment by snake0x65** [comment]
Perhaps we need to rewrite this code in the future, I was just making it work. My main concern was around both audio streams enabled . We should think about whole implementation as soon as we have time to think carefully.
