### ISSUE TITLE
Question: Is there a reason why both HS and Speaker are unmuted in cleanup?

### ISSUE THREAD

**Issue by stefdb** [snake0x65/hda#6]
https://github.com/snake0x65/hda/blob/e44851ad85fe97370127432325b65d4b1cbdd2c3/patch_cirrus.c#L1951-L1952

Not really and issue, more of a question:
Is there a reason why both HS and Speaker are unmuted in cleanup, rather than both being muted?

**Comment by snake0x65** [comment]
No reason for that, just did not have time to think properly.
