### ISSUE TITLE
Question: Volume

### ISSUE THREAD

**Issue by stefdb** [snake0x65/hda#7]
https://github.com/snake0x65/hda/blob/e44851ad85fe97370127432325b65d4b1cbdd2c3/patch_cirrus.c#L1938-L1941

The Volume for ASP1 and ASP2 is set to 0dB permanently, is there a way to change volume?

**Comment by snake0x65** [comment]
Currently we do not have any alsa controls for that, but I guess this what will be needed. You can have a look at other codec patches and make some nice controls. They also should be visible in aslamixer. Currently we have only one main PCM volume there.

**Comment by stefdb** [comment]
I tried adjusting the volume through the UI and it seemed to work - not sure if its just changing the volume through the stream or of there is something else, but something is there working.
